DROP TABLE BRAND;

CREATE TABLE BRAND (
	BRAND_ID	CHAR(5)		  PRIMARY KEY,
	BRAND_NAME	NVARCHAR2(30) NOT NULL
);

DROP TABLE CAR;

CREATE TABLE CAR (
	CAR_ID	    CHAR(5)		  PRIMARY KEY,
	CAR_NAME	NVARCHAR2(50) NOT NULL,
	CAR_SPECIES	NVARCHAR2(10) NOT NULL,
	CAR_FUEL	NVARCHAR2(15) NOT NULL,
	CAR_BIRTH	DATE		  DEFAULT SYSDATE,
	BRAND_ID	CHAR(5),
	FOREIGN KEY(BRAND_ID) REFERENCES BRAND
);

SELECT * FROM BRAND;

SELECT * FROM CAR;
