DROP TABLE CAT;

CREATE TABLE CAT(
	CAT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	CAT_NAME VARCHAR2(30) NOT NULL,
	CAT_GENDER VARCHAR2(10) NOT NULL,
	CAT_WEIGHT NUMBER NOT NULL,
	CAT_BIRTH DATE DEFAULT TRUNC(SYSDATE)
);

DROP TABLE HOUSE_KEEPER;

CREATE TABLE HOUSE_KEEPER(
	HOUSE_KEEPER_ID NUMBER GENERATED ALWAYS AS IDENTITY,
	HOUSE_KEEPER_NAME NVARCHAR2(30) NOT NULL,
	CAT_ID NUMBER NOT NULL,
	FOREIGN KEY(CAT_ID) REFERENCES CAT
);

DROP TABLE CAT_BOARD;

CREATE TABLE CAT_BOARD(
	CAT_BOARD_ID NUMBER GENERATED ALWAYS AS IDENTITY,
	CAT_ID NUMBER NOT NULL,
	CAT_BOARD_DATE DATE DEFAULT SYSDATE,
	FOREIGN KEY(CAT_ID) REFERENCES CAT
);

SELECT * FROM CAT;

SELECT * FROM HOUSE_KEEPER;

SELECT * FROM CAT_BOARD;