CREATE SEQUENCE SEQ_CAT_KEEPER
 START WITH 1
 NOCACHE;

DROP SEQUENCE SEQ_CAT;

CREATE SEQUENCE SEQ_CAT
 START WITH 1
 NOCACHE;

CREATE SEQUENCE SEQ_CAT_BOARD
 START WITH 1
 NOCACHE;

CREATE TABLE CAT_KEEPER(
	CAT_KEEPER_ID NUMBER PRIMARY KEY,
	CAT_KEEPER_NAME NVARCHAR2(30) NOT NULL
);

CREATE TABLE CAT(
	CAT_ID NUMBER PRIMARY KEY,
	CAT_NAME VARCHAR2(30) NOT NULL,
	CAT_GENDER VARCHAR2(10) NOT NULL,
	CAT_WEIGHT NUMBER NOT NULL,
	CAT_BIRTH DATE DEFAULT TRUNC(SYSDATE),
	CAT_KEEPER_ID NUMBER,
	FOREIGN KEY(CAT_KEEPER_ID) REFERENCES CAT_KEEPER
);

CREATE TABLE CAT_BOARD(
	CAT_BOARD_ID NUMBER PRIMARY KEY,
	CAT_BOARD_TITLE VARCHAR2(2000) NOT NULL,
	CAT_BOARD_CONTENT VARCHAR2(2000) NOT NULL,
	CAT_BOARD_DATE DATE DEFAULT SYSDATE,
	CAT_ID NUMBER NOT NULL,
	CAT_KEEPER_ID NUMBER NOT NULL,
	FOREIGN KEY(CAT_ID) REFERENCES CAT,
	FOREIGN KEY(CAT_KEEPER_ID) REFERENCES CAT_KEEPER
);

DROP TABLE CAT_BOARD;

DROP TABLE CAT;

DROP TABLE CAT_KEEPER;

SELECT * FROM CAT ORDER BY CAT_ID DESC;

SELECT * FROM CAT_KEEPER ORDER BY CAT_KEEPER_ID DESC;

SELECT * FROM CAT_BOARD ORDER BY CAT_BOARD_ID DESC;

SELECT 
	   CAT_NAME
	 , CAT_KEEPER_NAME  
  FROM 
  	   CAT
  JOIN
  	   CAT_KEEPER USING(CAT_KEEPER_ID);




